const {spawn} = require('child_process');
const fs = require('fs');
const bun = 'node_modules/@oven/bun-windows-x64/bin/bun.exe';
const p = spawn(bun, ['src-open/index.tsx'], {cwd: process.cwd(), stdio: ['ignore', 'pipe', 'pipe']});
let out = '', err = '';
p.stdout.on('data', d => out += d);
p.stderr.on('data', d => err += d);
const killTimer = setTimeout(() => { fs.writeFileSync('run-diag.txt', 'KILLED_AFTER_15S\n---OUT---\n' + out + '\n---ERR---\n' + err); p.kill(); }, 15000);
p.on('exit', (c, s) => { clearTimeout(killTimer); fs.writeFileSync('run-diag.txt', 'exit=' + c + ' signal=' + s + '\n---OUT---\n' + out + '\n---ERR---\n' + err); });
setTimeout(() => process.exit(0), 20000);
