"""Recognize user-role messages generated by the harness rather than the user."""

from __future__ import annotations


HARNESS_INJECTION_PREFIXES = (
    "<reminder>",
    "<task_notification>",
    "<session-context>",
    "<runtime-context>",
    "<persisted-output",
    "[Harness]",
    "[Skill loaded:",
    "[Compacted. Continue",
    "[Compacted]",
    "[Reactive compact]",
    "[Session resumed]",
    "[Resume context]",
    "[Inbox]",
    "[Scheduled]",
    "[snipped ",
)


def is_harness_injection_text(text: str) -> bool:
    """True when text is an internal notification, not a user instruction."""
    return text.lstrip().startswith(HARNESS_INJECTION_PREFIXES)
